is09-souzou/portal-web

src/components/GraphQLProgress.tsx, src/components/Header.tsx, src/components/page/Profile.tsx, src/components/page/UserListPage.tsx, src/components/page/UserPage.tsx
GraphQL Queryを発行中のLoading画面として `Loading...` として表示していたものを Material DesignのCircle Progressにに変更。
- Circle Progress
親要素の左右中央に配置するよう、 `GraphQLProgress.tsx` を作成。
=> UPDATE Display circle progress when GraphQL Query loading

src/components/wrapper/NotificationListener.tsx
notificationListenerで余計なElementが使われていたので修正
- notificationListener.tsx
```jsx
<div>
...
</div>
```
to
```jsx
<Fragment>
...
</Fragment>
```
- 特になし
- 特になし
エラー通知系で表示バグがあったような...
遭遇したら教えて
=> FIX notificationListener div -> Fragment

src/components/page/Profile.tsx
アバター画像を変更した後に、localの画像が変わっらない問題の修正。
- Profile.tsx
- S3へのアップロードおよびAppSyncのmutationの発酵後にRootのQueryのrefetchを呼び出す.
- 特になし.
- 特になし.
headerに今後Avatarを乗せる場合、同様の変更が必要になってくる可能性がある.
=> Add refetch Query after mutation avatar image

src/components/page/CreateWorkPage.tsx
https://github.com/is09-souzou/portal-web/issues/12 の修正.
AppSyncの型は変更せずに初期URLをmodelに追加.
画像自体は http://placehold.jp/ にて作成.
S3 bucketに `system` ディレクトリを追加し `broken-image.png` という名前で作成.
https://s3-ap-northeast-1.amazonaws.com/is09-portal-image/system/broken-image.png
- CreateWorkPage.tsx
- 特になし.
- 特になし.
https://github.com/is09-souzou/AppSync-Resolver-Mapping-Lambda/issues/5 の修正に入る.
=> Add Initial Image URL before upload Image to S3 on CreateWrokPage.tsx

src/components/Header.tsx, src/components/ImageInput.tsx, src/components/InitialRegistrationDialog.tsx, src/components/NotFound.tsx, src/components/page/Profile.tsx, src/components/wrapper/Auth.tsx
初回SignIn時、初期登録処理追加.
Header ComponentのUser情報取得時に、nullが返却された際にUser登録がされていないとみなしInitial Registration Dialogを表示する処理を追加.
同時に、
- Rerender毎にNotFountの顔文字がばらばらに表示されてしまうバグの修正
- Profile.tsxのコードレビュー、修正.
- src/components/Header.tsx
+ URLQueryParamにinitial-registration-dialogの管理
+ InitialRegistrationDialogの呼び出し.
- src/components/InitialRegistrationDialog.tsx
+ 追加
- src/components/NotFound.tsx
+ 変更
- src/components/page/Profile.tsx
+ コード修正
- src/components/wrapper/Auth.tsx
+ src/components/InitialRegistrationDialog.tsxのPropsにToken型を使用するため、Token Typeをexportするように修正
@alf852 が管理しているProfile.tsxの一部を修正.
特になし.
query getUserByIDの返り値がnullだった際に2回Redirectが発生してしまう.
=> Add Initial Registration dialog

src/components/page/Profile.tsx
Profile Pageでsign-outした際に無限ループが発生する問題。
tokenがない場合 `history.push()` を永遠に繰り返してしまうのでそこを修正.
同時に、tokenがない場合にHeaderを表示するよう変更.
認証してない状態でProfile Pageを開いた際に、Sign-inDialogが表示されるように変更.
特になし.
=> Fix: Infinite loop when signing out in the signature cancellation token state

src/components/InitialRegistrationDialog.tsx
#22  の修正.
InitialRegistrationDialogのMutationにてupdate時にGraphQLのキャッシュにUserInformationを書き込むよう変更.
- 特になし.
- 特になし.
#22 の解決.
=> Write cache when mutation of GraphQL

src/components/page/CreateWorkPage.tsx
https://github.com/is09-souzou/AppSync-Resolver-Mapping-Lambda/pull/20
https://github.com/is09-souzou/AppSync-Rule/pull/2
上記に伴う修正
`:%s/imageUri/imageUris/g`
`CreateWorkPage` を編集中のブランチ類の修正に入る
=> refactor: rename imageUri to imageUris

src/components/wrapper/AppSyncClient.tsx
jwtTokenがない状態でGraphQL Queryを発行するとエラーが発生する問題.
- AppSyncClient.tsx
+ `AWSAppSyncClient` の `jwtToken` に渡す関数の修正.
- 特になし。
- 特になし。
- 特になし。
=> Check whether the token of the prop is undefined

src/components/page/WorkListPage.tsx, src/graphQL/type.ts
Work PageをGrid designに修正.
現状余数での割り当てのため今後必要に応じて変更する予定.
同時に製作者名を表示するためAppSyncも修正.
https://github.com/is09-souzou/AppSync-Rule/pull/8
- src/graphQL/type.ts
+ User typeの追加
+ Work typeにuser要素を追加
- src/components/page/WorkListPage.tsx
+ レイアウト、ロジックの修正.
=> Migrate to grid design of work page

src/components/page/CreateWorkPage.tsx
#60 
- createWorkPageのworkContentAreaの両方に`overflow: auto`が設定され、中の左側の`div`に横スクロールバーが表示されていたが不要であるため右側の`div`のみに`overflow: auto`を設定した。
=> style(CreateWorkPage.tsx): update scroll bar on work content area

src/components/WorkDialog.tsx
close #62  
- workDialogの右側のマークダウンで掲載画像の解像度が大きいときにはみ出て表示されてしまっていた為`max-width: 100%`に変更した。
- マークダウンの`margin: 1rem`はダサかったので`padding: 1rem 1.5rem;`に変更した。
=> style(WorkDialog.tsx): update markdown on work content

src/components/organisms/InitialRegistrationDialog.tsx, src/components/organisms/WorkDialog.tsx, src/components/pages/ProfilePage/index.tsx, src/components/pages/SettingsPage/index.tsx, src/components/pages/WorkPostPage/index.tsx, src/components/pages/WorkUpdatePage/index.tsx
作品投稿が `create-work` pageでできない。
`titleInputElement` の `current` が存在しないというエラー
Title用の`TextField` に `inputRef` を適用していないことが問題
該当箇所の修正と、titleInputElement.currentが存在しなかった際のエラーハンドルを追加
=> Catch error when post work on `/create-work` page

package.json, src/components/molecules/Header.tsx, src/components/organisms/InitialRegistrationDialog.tsx, src/components/organisms/SignInDialog.tsx, src/components/organisms/SignUpDialog.tsx, src/components/wrappers/MainLayout.tsx
**今回の問題**
初期登録用のDialogが表示されない問題。
原因: 
Header componentで各Dialogの状態を管理しており、InitialRegistrationDialogの表示もHeader Componentで管理していたが、Profile PageのHeaderのマイグレーションにより、 `/profile` の時にDialogが表示されなかった。
Auth系のDialogの管理をHeader ComponentsからMainLayout Componentへと移行した。
Auth系Dialog一覧
- SignUpDialog
- SignInDialog
- InitialRegistrationDialog
今までは Header componentでURLの状態の判別を行い、表示非表示、ボタンを押した時の動作などの管理を行っていたがそれらを、それぞれのAuth系のDialogで管理させるように変更した。
また、前回の大規模リファクタの際に技術的負債の修正を一部行ったため、これらのAuth系Dialogが `MainLayout`  Component へ移行できなかった問題を同時に解決した。
This closes #
=> Migrate auth dialogs to MainLayout from header

package.json, src/components/organisms/SignInDialog.tsx, src/components/organisms/SignUpDialog.tsx, src/localization/locale.ts
Portalでは、Passwordの再入力の煩わしさをなくすために１回のみのパスワード入力で登録できるようになっているが、入力したパスワードを確認するすべがないため確認機能を実装
https://material-ui.com/demos/text-fields/#inputs
を参考にした。
上の画像のようにボタンで可視化を切り替えできるように変更。
SignIn DialogとSignUp Dialogに適応
=> Toggle password visibility

package.json, src/index.html
Designカレッジとの共同開発のため、できる限り限定公開にする必要がある。
そのために google analytics関連のソースコードを一時的にコメントアウトし無効化する。
また、Deployされたかの判別のためにバージョンの更新を行う。
=> Disable google analytics

src/components/pages/ProfilePage/index.tsx, src/components/pages/UserPage/index.tsx, src/localization/locale.ts
UserHeaderを表示しているcomponentでは、Userの情報が必要であるという都合上
- user取得のQueryの発行中
- user取得のQueryのError
- Userが存在しない
場合にユーザが操作するHeaderが存在しなかった。
そのため、得にモバイル端末からアクセスしたクライアントが、上記状況下にて操作ができない状況に陥っていた。
ソリューションとして、UserHeaderが表示されるまでの段階では、通常のHeader Componentを表示するよう変更した。
=> Add Header  Component when catch error or not found for control page

src/components/organisms/MarkdownSupports.tsx, src/components/pages/WorkPostPage/ActionArea.ts, src/components/pages/WorkPostPage/ActionButtonWrapper.ts, src/components/pages/WorkPostPage/ChipList.ts, src/components/pages/WorkPostPage/Head.ts, src/components/pages/WorkPostPage/Host.ts, src/components/pages/WorkPostPage/WorkContentArea.ts, src/components/pages/WorkPostPage/index.tsx
モバイルからの利用率が想定より高く、モバイルの操作性に特化したデザインに変更する必要があると判断。
現状一番ひどいと思った Work post pageの修正を行う。
主にCSSの修正のみで対応する。
**Before**
**After**
=> Update work post page ui for mobile

package.json, src/components/pages/WorkListPage/index.tsx, src/components/wrappers/AppSyncClient.tsx, src/components/wrappers/ErrorBoundary.tsx
- `query.data` の中身が空の場合の処理を追加
- AWS Lambdaを使用しているときは、`disableOffline: true` をAppSync client constructorに記載しなければならないと[公式Guide](https://docs.aws.amazon.com/ja_jp/appsync/latest/devguide/building-a-client-app-node.html)に書いてあったのでそのように追加
- Debug用にerror時のlogを表示するように変更
This closes #
=> Fix can not open page of iphone or safari

src/components/atoms/WorkItem.tsx, src/components/molecules/Header.tsx, src/components/molecules/Navigator.tsx, src/components/molecules/UserHeader.tsx, src/components/organisms/MarkdownHintDialog.tsx, src/components/organisms/SignUpDialog.tsx, src/components/organisms/WorkDialog.tsx, src/components/pages/ProfilePage/ProfileContent.ts, src/components/pages/ProfilePage/UserAvatar.tsx, src/components/pages/ProfilePage/index.tsx, src/localization/locale.ts
デザインカレッジとのレビューで出たUIの改修
- 画像ズームがいらない(もしくは画像ズームするとき斜めに曲げなくていい)(消す)
- WorkDialogの画像をhoverした時のズームを削除
- ユーザーアイコンを拡大して表示したい
- UserPageでユーザーアイコンをクリックしたときに画像を拡大して表示するように変更
- ユーザーのアイコンが変わらない
- ProfilePageにてユーザーアイコンの更新ができるように変更
- スマホ版のWorkListPageの作者の文字が小さいかも
- スマホ版のWorkListPageの作者の文字を拡大
- Header右上が現在はただのIconになっているが、ここに自身のユーザアイコンが出て欲しい
- ユーザアイコンが表示されるように変更
- SignUp時、パスワードの制限が分かりづらい
- helperTextで制限を表記
上記の変更に伴うLocalizationの適応
- atoms
- WorkItem.tsx
- molecules
- Header.tsx
- Navigator.tsx
- UserHeader.tsx
- organisms
- MarkdownHintDialog.tsx
- SignUpDialog.tsx
- WorkDialog.tsx
- pages
- ProfilePage
- ProfileContent.ts
- UserAvatar.tsx
- index.tsx
- localization
- locale.ts
This closes #
=> Fixed the UI pointed out by reviewers
