package.json

package.jsonのバージョン更新
バージョン管理のため。
- package.json
- なし
- なし
pull reqの練習で行いました。

FIX package.json

---

src/App.tsx
src/components/Fab.tsx
src/components/Header.tsx
src/components/Page.tsx
src/components/page/CreateWorkPage.tsx
src/components/page/Profile.tsx
src/components/page/UserListPage.tsx
src/components/page/UserPage.tsx
src/components/page/WorkPage.tsx
src/components/wrapper/MainLayout.tsx

https://github.com/is09-souzou/portal-web/issues/14
- MainLayoutからHeaderとFABを削除。
+ 現状APIを事実上持っていない。
- Page Componentの作成
- Fab Componentの作成
- 各ページの対応
MainLayout下すべて
- 特になし
- 特になし

migration of fab and header management component

---

package-lock.json
package.json
src/components/Header.tsx
src/components/SignUpDialog.tsx
src/components/wrapper/AppSyncClient.tsx
src/components/wrapper/Auth.tsx
src/config.ts
yarn.lock

https://github.com/is09-souzou/portal-web/issues/17
- Cognito User Pool IDの変更
- Cognito Application Collaboration Keyの変更
- SignUpDialog周りの変更
- SignUp後のredirect URLの変更
変更ファイルのみ
独自に作成したAPIの変更は特になし
- 特になし.

migration-cognito-user-pool (#17)

---

src/components/page/Profile.tsx
src/components/wrapper/Auth.tsx

- Update Emailの実装
- Setting用のdivの追加
- src/components/page/Profile.tsx
- src-components/wrapper/Auth.tsx
CognitoのEmail属性は変更できたのですが、そのメールアドレスの認証がうまくいっていません。
自分でも色々試してみたのですが、出来ませんでした。
申し訳ありませんが、お力添えをお願いいたします。

Add Update Email

---

src/components/page/Profile.tsx
src/components/wrapper/Auth.tsx

- add update passwordの作成
- UIの設定
- src/components/page/Profile.tsx
- src-components/wrapper/Auth.tsx
- 現状入力後buttonを押してもPOSTエラーが出ます。

Add Update Password

---

src/components/page/Profile.tsx

#11 
/src/components/page/Profile.tsx

fix new avatar image

---

src/components/Navigator.tsx
src/components/wrapper/MainLayout.tsx

NavigationBarの実装をした。
まだ途中段階.
同時にtypo修正　

Display searching work tags

---

src/components/page/CreateWorkPage.tsx

- src/components/page/CreateWorkPage.tsx
のバグ修正

HotFix: Modify GraphQL Query

---

src/components/page/CreateWorkPage.tsx

Fix: Create work

---

src/components/Header.tsx
src/components/Navigator.tsx
src/components/page/Profile.tsx
src/components/page/UserListPage.tsx
src/components/page/UserPage.tsx

Error handling patch, rename error word

---

package.json
src/components/Image.tsx
src/components/ImageInput.tsx
src/components/WorkDialog.tsx
src/components/page/CreateWorkPage.tsx
src/components/page/WorkListPage.tsx
src/components/wrapper/MainLayout.tsx
src/graphQL/type.ts
yarn.lock

Workの投稿内容をmarkdownに変更する作業.
- package
+ Add: react-markdown
- Image
+ Update: image
- Main Layout/Image Input
+ Fix: height lenge
- Work Dialog/Work List Page
+ Fix: multiple image -> sigle image
- graphql/type.ts
+ update work type
- Workを使用する全て
Markdownは脆弱性の検証までは Domはエスペープする.

Feature(markdown): Create work page

---

src/components/WorkDialog.tsx

WorkDialogのレイアウト変更
WorkDialog.tsx
まだ昨日のレビューでいただいた変更点は修正できてないです

[fix] work dialog layout

---

src/App.tsx
src/components/ErrorPage.tsx
src/components/Header.tsx
src/components/InitialRegistrationDialog.tsx
src/components/Navigator.tsx
src/components/WorkDialog.tsx
src/components/page/CreateWorkPage.tsx
src/components/page/Profile.tsx
src/components/page/UserListPage.tsx
src/components/page/UserPage.tsx
src/components/page/WorkListPage.tsx
src/components/wrapper/Auth.tsx
tslint.json

Style work dialog

---

src/components/page/WorkListPage.tsx

#44
runtimeエラーの緊急修正.
required environment variables and dependency update -->
一時的なものなので今後別ロジックに置き換え必須

Add handle when workConnection is undefined.

---

src/components/Navigator.tsx

View error list item at catch error

---

src/components/page/CreateWorkPage.tsx

#58 
- `CreateWorkPage`にある`TextField`3つを上部の画像のように`placeholder`と`label`を変更した。

style(CreateWorkPage.tsx): update text field

---

src/components/Header.tsx
src/components/WorkList.tsx

#53
sing-in時にpopoverを表示させないように変更
src/Header.tsx
src/WorkList.tsx

Can not hide popover content

---

src/components/page/ProfilePage.tsx

#52  
- Profile画面にてDisplayNameは4文字以上の文字しかSAVEできないように変更
- ProfilePage.tsx

style(ProfilePage.tsx): update callupdateuser

---

src/components/FormatStringDate.tsx
src/components/WorkDialog.tsx
src/components/page/WorkListPage.tsx
tslint.json

#64 
Apolloのrefetch関連の物を使用
同時に https://github.com/is09-souzou/AppSync-Resolver-Mapping-Lambda/issues/33 の修正
-  特になし
-  特になし
This closes #64

modify control pagination item

---

src/index.html

#82 
`src/index.html`
This closes #82

Add the google tag manager

---

src/components/wrapper/Auth.tsx
src/index.html

- Auth.tsxから伝搬されるpropsの追加
+ idToken
+ clientPayload
+ cognitoUser
- ついでにconsoleに表示されるうさぎのズレを修正
- Auth.tsx
- index.html
追加のみなので特に
特にないです
issueはたててないです
このPRにて `auth.clientPayload` からsignin状態のuserのpayloadを取得できます。

Add properties on Auth.tsx

---

src/index.html

- consoleに表示される`PORTAL`の`L`の右側の余白を追加
- index.html
なし
なし

fix(index): refactor

---

src/components/page/WorkPostPage.tsx

公開・非公開のトグルボタンを実装
src/components/page/WorkPostPage.tsx
関連するAWS側の設定:https://github.com/is09-souzou/AppSync-Resolver-Mapping-Lambda/pull/36
This closes #

Switch(Toggle-Button) on PostWorkPage

---

src/components/Fab.tsx
src/components/Header.tsx
src/components/page/ProfilePage.tsx
src/components/page/UserPage.tsx
src/localization/locale.ts

プロフィールページをユーザーページと同じデザインに変更
スキルリスト項目を追加
- ProfilePage.tsx
- Header.tsx
- locale.ts
This closes #

Update on Profile Page

---

src/components/page/UserPage.tsx
src/components/wrapper/AppSyncClient.tsx
src/config.ts
yarn.lock

- 公開APIへの対応
- AppSyncClient.tsx
- 全体

Compatible with public API

---

.circleci/config.yml
package.json

Deployの自動化
同時にTestの修正
- Circle ciのversionを2.1に変更
- NodeJSのバージョンを変更できるよう修正
- master branchにpushが入った際に test -> build -> deployを行うよう修正
- Testの一部修正
This closes #

Feature Auto deploy

---

.circleci/config.yml

Fix auto deploy

---

src/App.tsx
src/Routes.ts
src/components/pages/NotFoundPage/Content.ts
src/components/pages/NotFoundPage/index.tsx
src/localization/locale.ts

存在しないページにアクセスされた際に Not Found Pageを表示させる。
NotFoundPageの作成
React RouterのSwitchにて該当するパターンがない場合NotFoundPageを表示

Feat NotFoundPage

---

src/index.html
src/index.tsx
webpack.config.js

Deployされてる環境のバージョンの確認のためにconsole.logにversionを表示するように変更。
同時にNODE_ENVの表示も行う
こんな感じです

Display service version to console log

---

src/components/pages/UserPage/UserPageHeader.tsx
src/components/pages/UserPage/index.tsx

部分的な細かな修正を行った。
同時に `package.json` のversionをこの段階で `1.0.0` へと変更した。
今後、 `develop` branch が作成されるまで、どの段階でバージョンを更新していくか要検討

Update user page style

---

package.json

Versionの更新を行う。
Versionの管理方法はまだ決めていないので要検討
関連PR #111

Update version to 1.0.0

---

src/components/pages/WorkPostPage/index.tsx

一度の投稿でworkが二つ生成される問題の修正
#117 
- WorkPostPage/index.tsx
This closes #

Fix two works are posted

---

package.json
src/Root.tsx
src/components/molecules/Navigator.tsx
src/components/organisms/InitialRegistrationDialog.tsx
src/components/organisms/SignInDialog.tsx
src/components/organisms/SignUpDialog.tsx
src/components/wrappers/AppSyncClient.tsx
src/components/wrappers/Auth.tsx
src/components/wrappers/ErrorBoundary.tsx
src/components/wrappers/MainLayout.tsx
src/contexts/AuthContext.ts
src/localization/locale.ts

https://github.com/is09-souzou/portal-web/issues/121
https://github.com/is09-souzou/portal-web/issues/123
の修正用 **hotfix branch**
ErrorBoundaryの実装を行った。
以上発生時にホワイトアウトしないようにした
ErrorBoundary自体でエラーが発生しないように必要最低限の実装しかしないようにした。

[WIP] Can not registration user
